name: "Wachirawat"

on:
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-22.04
    outputs:
      image_name: ${{ steps.unit_test.outputs.image_name }}
    steps:
    - name: Unit test
      id: unit_test
      run: |
        echo "Unin test"
        echo "image_name=IMAGE" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-22.04
    needs:
      - test
    steps:
    - name: Build
      id: build
      env:
        image_name: ${{ needs.test.outputs.image_name }}
      run: |
        echo "image_name: ${{ needs.test.outputs.image_name }}"
        echo "image_name: ${{ needs.test.outputs.image_name }}"
        echo "The value of image_name is $image_name"
  
