name: "Wachirawat"

on:
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - name: Unit test
      run: |
        echo "Unin test"
        echo "MY_ENV_VAR=VALUE" >> $GITHUB_ENV
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Build
      run: |
        echo "The value of MY_ENV_VAR is $MY_ENV_VAR"
  
